name: qr_code_generator
description: A Flutter package for generating dynamic QR codes with custom colors using CustomPainter.
version: 1.0.1
homepage: https://github.com/rasel2510/qr_code_generator
repository: https://github.com/rasel2510/qr_code_generator

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
